# Generated by Django 6.0.6 on 2026-06-20 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='base_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='apikey',
            name='transfer_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
