# Generated by Django 6.0.6 on 2026-06-23 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_set_base_name_for_existing_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='electricity_rate_kwh',
            field=models.DecimalField(decimal_places=4, default=0.12, help_text='Electricity cost per kWh', max_digits=6),
        ),
    ]
