# Generated by Django 6.0.6 on 2026-06-23 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_electricity_rate_kwh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='electricity_rate_kwh',
            field=models.DecimalField(decimal_places=4, default=0.33, help_text='Electricity cost per kWh', max_digits=6),
        ),
    ]
