# Generated by: python manage.py makemigrations accounts --name add_api_key_lookup
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0007_update_electricity_rate_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='key_lookup',
            field=models.CharField(
                max_length=64,
                null=True,
                blank=True,
                db_index=True,
                help_text="HMAC-SHA256 lookup identifier for fast database lookup",
            ),
        ),
    ]