# Generated by Django 6.1.1 on 2026-09-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_add_api_key_lookup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='key_hash',
            field=models.CharField(help_text='Argon2 hash used to cryptographically verify the plaintext API key.', max_length=255),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='key_lookup',
            field=models.CharField(blank=True, db_index=True, help_text='HMAC-SHA256 lookup identifier used to find the corresponding API key efficiently.', max_length=64, null=True),
        ),
    ]
