# Generated by Django 6.0.6 on 2026-06-19 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rigs', '0002_rig_latest_errors'),
    ]

    operations = [
        migrations.AddField(
            model_name='rig',
            name='_seen_error_hashes_json',
            field=models.JSONField(blank=True, db_column='seen_error_hashes_json', default=list),
        ),
        migrations.AddField(
            model_name='rig',
            name='error_history_json',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
