# Generated by Django 6.0.5 on 2026-06-15 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rigs', '0002_rig_latest_errors'),
    ]

    operations = [
        migrations.AddField(
            model_name='rig',
            name='cpu_logical_cores',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rig',
            name='cpu_model',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='rig',
            name='cpu_physical_cores',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rig',
            name='docker_version',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='rig',
            name='gpu_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rig',
            name='gpu_profiles_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='rig',
            name='hostname',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='rig',
            name='kernel',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='rig',
            name='mem_total_bytes',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rig',
            name='motherboard_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='rig',
            name='network_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rig',
            name='network_profiles_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='rig',
            name='nvidia_driver',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='rig',
            name='os_distro',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='rig',
            name='storage_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rig',
            name='storage_profiles_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='rig',
            name='swap_total_bytes',
            field=models.BigIntegerField(null=True),
        ),
    ]
