# Generated by Django 6.0.6 on 2026-06-20 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_display_name'),
        ('rigs', '0003_rig_error_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='rig',
            name='enrolled_by_api_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolled_rigs', to='accounts.apikey'),
        ),
    ]
