# Generated by Django 6.0.6 on 2026-06-23 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rigs', '0004_rig_enrolled_by_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='rig',
            name='electricity_rate_kwh',
            field=models.DecimalField(decimal_places=4, default=0.12, help_text='Electricity cost per kWh', max_digits=6),
        ),
        migrations.AddField(
            model_name='rig',
            name='psu_efficiency',
            field=models.DecimalField(decimal_places=2, default=0.9, help_text='PSU efficiency (0.85=Bronze, 0.90=Gold, 0.92=Platinum)', max_digits=3),
        ),
    ]
