# Generated by Django 6.0.6 on 2026-06-23 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rigs', '0005_rig_electricity_rate_kwh_rig_psu_efficiency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rig',
            name='psu_efficiency',
        ),
    ]
