# Generated by Django 6.0.6 on 2026-06-23 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rigs', '0006_remove_rig_psu_efficiency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rig',
            name='electricity_rate_kwh',
        ),
    ]
