# Generated by Django 6.0.6 on 2026-06-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rigs', '0007_remove_rig_electricity_rate_kwh'),
    ]

    operations = [
        migrations.AddField(
            model_name='rig',
            name='_seen_container_hashes_json',
            field=models.JSONField(blank=True, db_column='seen_container_hashes_json', default=list),
        ),
        migrations.AddField(
            model_name='rig',
            name='container_history_json',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
