# Generated by Django 6.0.5 on 2026-06-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LatestSnapshot',
            fields=[
                ('rig_uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('schema_version', models.CharField(default='1.0', max_length=10)),
                ('timestamp', models.DateTimeField()),
                ('cpu_utilization_pct', models.FloatField(null=True)),
                ('cpu_temp_c', models.FloatField(null=True)),
                ('mem_used_bytes', models.BigIntegerField(null=True)),
                ('mem_total_bytes', models.BigIntegerField(null=True)),
                ('gpu_metrics_json', models.JSONField(blank=True, default=list)),
                ('storage_json', models.JSONField(blank=True, default=list)),
                ('network_json', models.JSONField(blank=True, default=list)),
                ('docker_containers_json', models.JSONField(blank=True, default=list)),
                ('software_json', models.JSONField(blank=True, default=dict)),
                ('errors_json', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'metrics_latest_snapshot',
            },
        ),
        migrations.CreateModel(
            name='ErrorEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rig_uuid', models.UUIDField(db_index=True)),
                ('timestamp', models.DateTimeField()),
                ('source', models.CharField(blank=True, default='', max_length=50)),
                ('message', models.TextField(blank=True, default='')),
                ('hash', models.CharField(db_index=True, max_length=64)),
                ('count', models.PositiveIntegerField(default=1)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'metrics_lasterrors',
                'unique_together': {('rig_uuid', 'hash')},
            },
        ),
        migrations.CreateModel(
            name='MetricSnapshot',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rig_uuid', models.UUIDField(db_index=True)),
                ('schema_version', models.CharField(default='1.0', max_length=10)),
                ('agent_version', models.CharField(default='1.0.0', max_length=20)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('cpu_model', models.CharField(blank=True, default='', max_length=255)),
                ('cpu_utilization_pct', models.FloatField(null=True)),
                ('cpu_temp_c', models.FloatField(null=True)),
                ('cpu_physical_cores', models.PositiveIntegerField(null=True)),
                ('cpu_logical_cores', models.PositiveIntegerField(null=True)),
                ('mem_total_bytes', models.BigIntegerField(null=True)),
                ('mem_used_bytes', models.BigIntegerField(null=True)),
                ('mem_cached_bytes', models.BigIntegerField(null=True)),
                ('storage_json', models.JSONField(blank=True, default=list)),
                ('network_json', models.JSONField(blank=True, default=list)),
                ('gpu_metrics_json', models.JSONField(blank=True, default=list)),
                ('ai_processes_json', models.JSONField(blank=True, default=list)),
                ('docker_containers_json', models.JSONField(blank=True, default=list)),
                ('software_json', models.JSONField(blank=True, default=dict)),
                ('errors_json', models.JSONField(blank=True, default=list)),
                ('inventory_json', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'metrics_metricsnapshot',
                'indexes': [models.Index(fields=['rig_uuid', '-timestamp'], name='metrics_met_rig_uui_5543cc_idx')],
                'unique_together': {('rig_uuid', 'schema_version', 'timestamp')},
            },
        ),
    ]
