# Generated by Django 6.0.5 on 2026-06-02 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics_app', '0002_auto_20260602'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dockercontainermetric',
            new_name='metrics_doc_rig_uui_ccd705_idx',
            old_name='metrics_docker_rig_uuid_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='gpumetric',
            new_name='metrics_gpu_rig_uui_6fd8c2_idx',
            old_name='metrics_gpu_rig_uuid_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='networkmetric',
            new_name='metrics_net_rig_uui_59660a_idx',
            old_name='metrics_net_rig_uuid_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='storagemetric',
            new_name='metrics_sto_rig_uui_dd9581_idx',
            old_name='metrics_stor_rig_uuid_ts_idx',
        ),
    ]
