# Generated by Django 6.0.5 on 2026-06-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics_app', '0003_rename_metrics_docker_rig_uuid_ts_idx_metrics_doc_rig_uui_ccd705_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RigHardware',
            fields=[
                ('rig_uuid', models.UUIDField(db_index=True, primary_key=True, serialize=False)),
                ('cpu_model', models.CharField(blank=True, default='', max_length=255)),
                ('cpu_physical_cores', models.PositiveIntegerField(null=True)),
                ('cpu_logical_cores', models.PositiveIntegerField(null=True)),
                ('mobo_manufacturer', models.CharField(blank=True, default='', max_length=255)),
                ('mobo_model', models.CharField(blank=True, default='', max_length=255)),
                ('bios_version', models.CharField(blank=True, default='', max_length=255)),
                ('gpu_static_json', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'metrics_rig_hardware',
            },
        ),
        migrations.RemoveField(
            model_name='gpumetric',
            name='gpu_uuid',
        ),
        migrations.RemoveField(
            model_name='gpumetric',
            name='mem_total_mb',
        ),
        migrations.RemoveField(
            model_name='gpumetric',
            name='model',
        ),
        migrations.RemoveField(
            model_name='metricsnapshot',
            name='cpu_logical_cores',
        ),
        migrations.RemoveField(
            model_name='metricsnapshot',
            name='cpu_model',
        ),
        migrations.RemoveField(
            model_name='metricsnapshot',
            name='cpu_physical_cores',
        ),
        migrations.RemoveField(
            model_name='metricsnapshot',
            name='mem_total_bytes',
        ),
        migrations.RemoveField(
            model_name='storagemetric',
            name='capacity_bytes',
        ),
    ]
