# Generated by Django 6.0.5 on 2026-06-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics_app', '0004_righardware_remove_gpumetric_gpu_uuid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RigHardware',
        ),
        migrations.RenameField(
            model_name='metricsnapshot',
            old_name='inventory_json',
            new_name='motherboard_json',
        ),
        migrations.AddField(
            model_name='gpumetric',
            name='gpu_uuid',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='gpumetric',
            name='mem_free_mb',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='gpumetric',
            name='mem_total_mb',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='gpumetric',
            name='model',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='metricsnapshot',
            name='cpu_logical_cores',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='metricsnapshot',
            name='cpu_model',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='metricsnapshot',
            name='cpu_physical_cores',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='metricsnapshot',
            name='mem_total_bytes',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='storagemetric',
            name='capacity_bytes',
            field=models.BigIntegerField(null=True),
        ),
    ]
