# Generated by Django 6.0.5 on 2026-06-06 02:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics_app', '0005_delete_righardware_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dockercontainermetric',
            name='cpu_pct',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='dockercontainermetric',
            name='mem_limit_bytes',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='dockercontainermetric',
            name='mem_usage_bytes',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='metricsnapshot',
            name='cpu_load_avg_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='metricsnapshot',
            name='mem_free_bytes',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='metricsnapshot',
            name='status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='metricsnapshot',
            name='swap_total_bytes',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='metricsnapshot',
            name='swap_used_bytes',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='networkmetric',
            name='rx_bytes_delta',
            field=models.BigIntegerField(help_text='Bytes received since last reading', null=True),
        ),
        migrations.AddField(
            model_name='networkmetric',
            name='tx_bytes_delta',
            field=models.BigIntegerField(help_text='Bytes sent since last reading', null=True),
        ),
        migrations.CreateModel(
            name='RigStatusEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rig_uuid', models.UUIDField(db_index=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('status', models.CharField(db_index=True, max_length=10)),
                ('previous_status', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'metrics_rig_status_event',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['rig_uuid', '-timestamp'], name='metrics_rig_rig_uui_427e88_idx'), models.Index(fields=['rig_uuid', 'status'], name='metrics_rig_rig_uui_0bef0e_idx')],
            },
        ),
        migrations.CreateModel(
            name='AIProcessMetric',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rig_uuid', models.UUIDField(db_index=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('process_name', models.CharField(blank=True, default='', max_length=255)),
                ('pid', models.PositiveIntegerField(null=True)),
                ('gpu_uuid', models.CharField(blank=True, default='', max_length=64)),
                ('gpu_mem_used_mb', models.PositiveIntegerField(null=True)),
                ('cpu_pct', models.FloatField(null=True)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_processes', to='metrics_app.metricsnapshot')),
            ],
            options={
                'db_table': 'metrics_ai_process',
                'ordering': ['-gpu_mem_used_mb'],
                'indexes': [models.Index(fields=['rig_uuid', '-timestamp'], name='metrics_ai__rig_uui_8c4bce_idx'), models.Index(fields=['rig_uuid', 'process_name'], name='metrics_ai__rig_uui_d15e8e_idx')],
                'unique_together': {('rig_uuid', 'timestamp', 'process_name')},
            },
        ),
    ]
