# Generated by Django 6.0.5 on 2026-06-06 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics_app', '0006_dockercontainermetric_cpu_pct_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPUProcessMetric',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rig_uuid', models.UUIDField(db_index=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('gpu_index', models.PositiveSmallIntegerField(default=0)),
                ('pid', models.PositiveIntegerField(null=True)),
                ('process_name', models.CharField(blank=True, default='', max_length=500)),
                ('type', models.CharField(blank=True, default='', max_length=10)),
                ('gpu_mem_mb', models.PositiveIntegerField(null=True)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gpu_processes', to='metrics_app.metricsnapshot')),
            ],
            options={
                'db_table': 'metrics_gpu_process',
                'ordering': ['-gpu_mem_mb'],
                'indexes': [models.Index(fields=['rig_uuid', '-timestamp'], name='metrics_gpu_rig_uui_47b943_idx')],
                'unique_together': {('rig_uuid', 'timestamp', 'gpu_index', 'pid')},
            },
        ),
    ]
