# Generated by Django 6.0.5 on 2026-06-07 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics_app', '0007_gpu_process_metric'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='erroreventoccurrence',
            unique_together={('error_event', 'rig_uuid', 'timestamp')},
        ),
    ]
