# Generated by Django 6.0.5 on 2026-06-09 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics_app', '0009_pcie_link_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricsnapshot',
            name='error_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metricsnapshot',
            name='error_json',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
