# Generated by Django 6.0.5 on 2026-06-10 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics_app', '0012_gpu_clock_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='dockercontainermetric',
            name='container_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='dockercontainermetric',
            name='uptime_s',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
