# Generated by Django 6.0.5 on 2026-06-11 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics_app', '0013_dockercontainermetric_container_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dockercontainermetric',
            name='cpu_pct',
        ),
        migrations.RemoveField(
            model_name='dockercontainermetric',
            name='mem_limit_bytes',
        ),
        migrations.RemoveField(
            model_name='dockercontainermetric',
            name='mem_usage_bytes',
        ),
        migrations.RemoveField(
            model_name='dockercontainermetric',
            name='restart_count',
        ),
    ]
