# Generated by Django 6.0.5 on 2026-06-11 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics_app', '0014_remove_dockercontainermetric_cpu_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dockercontainermetric',
            name='cpu_pct',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='dockercontainermetric',
            name='mem_limit_bytes',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='dockercontainermetric',
            name='mem_usage_bytes',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='dockercontainermetric',
            name='restart_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
