# Generated by Django 6.0.5 on 2026-06-11 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics_app', '0015_dockercontainermetric_cpu_pct_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='aiprocessmetric',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='aiprocessmetric',
            name='metrics_ai__rig_uui_8c4bce_idx',
        ),
        migrations.RemoveIndex(
            model_name='aiprocessmetric',
            name='metrics_ai__rig_uui_d15e8e_idx',
        ),
        migrations.DeleteModel(
            name='AIProcessMetric',
        ),
    ]
