# Generated by Django 6.0.5 on 2026-06-11 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics_app', '0016_alter_aiprocessmetric_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dockercontainermetric',
            name='image',
        ),
        migrations.RemoveField(
            model_name='dockercontainermetric',
            name='restart_count',
        ),
        migrations.RemoveField(
            model_name='dockercontainermetric',
            name='snapshot',
        ),
        migrations.RemoveField(
            model_name='dockercontainermetric',
            name='status',
        ),
        migrations.RemoveField(
            model_name='dockercontainermetric',
            name='uptime_s',
        ),
        migrations.CreateModel(
            name='LatestDockerContainer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rig_uuid', models.UUIDField(db_index=True)),
                ('container_id', models.CharField(blank=True, default='', max_length=64)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('image', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(blank=True, default='', max_length=32)),
                ('uptime_s', models.PositiveIntegerField(null=True)),
                ('restart_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'metrics_latest_docker_container',
                'indexes': [models.Index(fields=['rig_uuid'], name='metrics_lat_rig_uui_7542ec_idx')],
                'unique_together': {('rig_uuid', 'name')},
            },
        ),
    ]
