# Generated by Django 6.0.5 on 2026-06-11 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics_app', '0017_remove_dockercontainermetric_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dockercontainermetric',
            name='mem_limit_bytes',
        ),
        migrations.AddField(
            model_name='latestdockercontainer',
            name='mem_limit_bytes',
            field=models.BigIntegerField(null=True),
        ),
    ]
