# Generated by Django 6.0.5 on 2026-06-12 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics_app', '0018_remove_dockercontainermetric_mem_limit_bytes_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='gpumetric',
            index=models.Index(fields=['rig_uuid', 'gpu_index', '-timestamp'], name='gpumetric_rig_gpu_ts_idx'),
        ),
    ]
