# Generated by Django 6.0.5 on 2026-06-12 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics_app', '0019_gpumetric_gpumetric_rig_gpu_ts_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestsnapshot',
            name='gpu_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='gpu_fans_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='gpu_models_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='gpu_temps_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='gpu_utils_json',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
