# Generated by Django 6.0.5 on 2026-06-15 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics_app', '0019_gpumetric_gpumetric_rig_gpu_ts_idx'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dockercontainermetric',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='dockercontainermetric',
            name='metrics_doc_rig_uui_ccd705_idx',
        ),
        migrations.DeleteModel(
            name='DockerContainerMetric',
        ),
        migrations.AlterUniqueTogether(
            name='latestdockercontainer',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='latestdockercontainer',
            name='metrics_lat_rig_uui_7542ec_idx',
        ),
        migrations.DeleteModel(
            name='LatestDockerContainer',
        ),
        migrations.RemoveField(
            model_name='gpumetric',
            name='gpu_uuid',
        ),
        migrations.RemoveField(
            model_name='gpumetric',
            name='mem_total_mb',
        ),
        migrations.RemoveField(
            model_name='gpumetric',
            name='model',
        ),
        migrations.RemoveField(
            model_name='gpumetric',
            name='pcie_max_gen',
        ),
        migrations.RemoveField(
            model_name='gpumetric',
            name='pcie_max_width',
        ),
        migrations.RemoveField(
            model_name='gpumetric',
            name='power_limit_w',
        ),
        migrations.RemoveField(
            model_name='metricsnapshot',
            name='cpu_logical_cores',
        ),
        migrations.RemoveField(
            model_name='metricsnapshot',
            name='cpu_model',
        ),
        migrations.RemoveField(
            model_name='metricsnapshot',
            name='cpu_physical_cores',
        ),
        migrations.RemoveField(
            model_name='metricsnapshot',
            name='mem_total_bytes',
        ),
        migrations.RemoveField(
            model_name='metricsnapshot',
            name='motherboard_json',
        ),
        migrations.RemoveField(
            model_name='metricsnapshot',
            name='software_json',
        ),
        migrations.RemoveField(
            model_name='metricsnapshot',
            name='swap_total_bytes',
        ),
        migrations.RemoveField(
            model_name='networkmetric',
            name='ipv4',
        ),
        migrations.RemoveField(
            model_name='networkmetric',
            name='link_speed_mbps',
        ),
        migrations.RemoveField(
            model_name='networkmetric',
            name='rx_bytes',
        ),
        migrations.RemoveField(
            model_name='networkmetric',
            name='tx_bytes',
        ),
        migrations.RemoveField(
            model_name='storagemetric',
            name='capacity_bytes',
        ),
        migrations.RemoveField(
            model_name='storagemetric',
            name='fstype',
        ),
        migrations.RemoveField(
            model_name='storagemetric',
            name='mountpoint',
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='docker_containers_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='gpu_core_clocks_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='gpu_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='gpu_fans_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='gpu_mem_clocks_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='gpu_mem_free_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='gpu_mem_total_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='gpu_mem_used_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='gpu_mem_util_pcts_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='gpu_models_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='gpu_pcie_gen_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='gpu_pcie_max_gen_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='gpu_pcie_max_width_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='gpu_pcie_width_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='gpu_power_draws_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='gpu_power_limits_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='gpu_temps_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='gpu_utils_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='mem_cached_bytes',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='mem_free_bytes',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='network_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='network_interfaces_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='network_ipv4s_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='network_rx_bytes_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='network_rx_errors_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='network_speeds_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='network_tx_bytes_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='network_tx_errors_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='storage_capacities_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='storage_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='storage_devices_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='storage_fstypes_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='storage_mountpoints_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='storage_smart_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='storage_temps_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='storage_usage_pcts_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='swap_total_bytes',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='swap_used_bytes',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='uptime_s',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='metricsnapshot',
            name='profile_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
