# Generated by Django 6.0.5 on 2026-06-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics_app', '0020_latestsnapshot_gpu_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestsnapshot',
            name='gpu_core_clocks_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='gpu_mem_clocks_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='gpu_mem_total_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='gpu_mem_used_json',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
