# Generated by Django 6.0.5 on 2026-06-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics_app', '0022_latestsnapshot_network_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestsnapshot',
            name='gpu_mem_free_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='gpu_mem_util_pcts_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='gpu_pcie_gen_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='gpu_pcie_max_gen_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='gpu_pcie_max_width_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='gpu_pcie_width_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='gpu_power_draws_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='gpu_power_limits_json',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
