# Generated by Django 6.0.5 on 2026-06-12 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics_app', '0023_latestsnapshot_gpu_mem_free_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestsnapshot',
            name='local_ip',
            field=models.CharField(blank=True, default='', max_length=45),
        ),
    ]
