# Generated by Django 6.0.5 on 2026-06-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics_app', '0023_latestsnapshot_gpu_mem_free_json_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dockercontainermetric',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='dockercontainermetric',
            name='metrics_doc_rig_uui_ccd705_idx',
        ),
        migrations.DeleteModel(
            name='DockerContainerMetric',
        ),
        migrations.RemoveField(
            model_name='latestdockercontainer',
            name='mem_limit_bytes',
        ),
        migrations.RemoveField(
            model_name='latestdockercontainer',
            name='restart_count',
        ),
        migrations.RemoveField(
            model_name='latestdockercontainer',
            name='uptime_s',
        ),
        migrations.AddField(
            model_name='latestdockercontainer',
            name='created',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='latestdockercontainer',
            name='status_text',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
