# Generated by Django 6.0.5 on 2026-06-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics_app', '0023_latestsnapshot_gpu_mem_free_json_and_more'),
    ]

    operations = [
        # DockerContainerMetric: unique_together and index already removed by migrations 0013-0017
        migrations.DeleteModel(
            name='DockerContainerMetric',
        ),
        migrations.RemoveField(
            model_name='latestdockercontainer',
            name='mem_limit_bytes',
        ),
        migrations.RemoveField(
            model_name='latestdockercontainer',
            name='restart_count',
        ),
        migrations.RemoveField(
            model_name='latestdockercontainer',
            name='uptime_s',
        ),
        migrations.AddField(
            model_name='latestdockercontainer',
            name='created',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='latestdockercontainer',
            name='status_text',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
