# Generated by Django 6.0.5 on 2026-06-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics_app', '0023_latestsnapshot_gpu_mem_free_json_and_more'),
    ]

    operations = [
        # DockerContainerMetric: table may or may not exist (already dropped on production).
        # Use SeparateDatabaseAndState: raw SQL for DB, DeleteModel for Django state.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='DockerContainerMetric',
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='DROP TABLE IF EXISTS metrics_dockercontainermetric CASCADE',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
        migrations.RemoveField(
            model_name='latestdockercontainer',
            name='mem_limit_bytes',
        ),
        migrations.RemoveField(
            model_name='latestdockercontainer',
            name='restart_count',
        ),
        migrations.RemoveField(
            model_name='latestdockercontainer',
            name='uptime_s',
        ),
        migrations.AddField(
            model_name='latestdockercontainer',
            name='created',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='latestdockercontainer',
            name='status_text',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
