# Generated by Django 6.0.5 on 2026-06-14 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics_app', '0024_docker_container_created_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RigProfile',
            fields=[
                ('rig_uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('cpu_model', models.CharField(blank=True, default='', max_length=255)),
                ('cpu_physical_cores', models.PositiveIntegerField(null=True)),
                ('cpu_logical_cores', models.PositiveIntegerField(null=True)),
                ('mem_total_bytes', models.BigIntegerField(null=True)),
                ('swap_total_bytes', models.BigIntegerField(null=True)),
                ('motherboard_json', models.JSONField(blank=True, default=dict)),
                ('hostname', models.CharField(blank=True, default='', max_length=255)),
                ('os_distro', models.CharField(blank=True, default='', max_length=255)),
                ('kernel', models.CharField(blank=True, default='', max_length=255)),
                ('nvidia_driver', models.CharField(blank=True, default='', max_length=64)),
                ('docker_version', models.CharField(blank=True, default='', max_length=64)),
                ('gpu_count', models.PositiveSmallIntegerField(default=0)),
                ('gpu_profiles_json', models.JSONField(blank=True, default=list)),
                ('storage_count', models.PositiveSmallIntegerField(default=0)),
                ('storage_profiles_json', models.JSONField(blank=True, default=list)),
                ('network_count', models.PositiveSmallIntegerField(default=0)),
                ('network_profiles_json', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rigs_rigprofile',
            },
        ),
        migrations.RemoveField(
            model_name='gpumetric',
            name='gpu_uuid',
        ),
        migrations.RemoveField(
            model_name='gpumetric',
            name='mem_total_mb',
        ),
        migrations.RemoveField(
            model_name='gpumetric',
            name='model',
        ),
        migrations.RemoveField(
            model_name='gpumetric',
            name='pcie_max_gen',
        ),
        migrations.RemoveField(
            model_name='gpumetric',
            name='pcie_max_width',
        ),
        migrations.RemoveField(
            model_name='gpumetric',
            name='power_limit_w',
        ),
        migrations.RemoveField(
            model_name='metricsnapshot',
            name='cpu_logical_cores',
        ),
        migrations.RemoveField(
            model_name='metricsnapshot',
            name='cpu_model',
        ),
        migrations.RemoveField(
            model_name='metricsnapshot',
            name='cpu_physical_cores',
        ),
        migrations.RemoveField(
            model_name='metricsnapshot',
            name='mem_total_bytes',
        ),
        migrations.RemoveField(
            model_name='metricsnapshot',
            name='motherboard_json',
        ),
        migrations.RemoveField(
            model_name='metricsnapshot',
            name='software_json',
        ),
        migrations.RemoveField(
            model_name='metricsnapshot',
            name='swap_total_bytes',
        ),
        migrations.RemoveField(
            model_name='networkmetric',
            name='ipv4',
        ),
        migrations.RemoveField(
            model_name='networkmetric',
            name='link_speed_mbps',
        ),
        migrations.RemoveField(
            model_name='networkmetric',
            name='rx_bytes',
        ),
        migrations.RemoveField(
            model_name='networkmetric',
            name='tx_bytes',
        ),
        migrations.RemoveField(
            model_name='storagemetric',
            name='capacity_bytes',
        ),
        migrations.RemoveField(
            model_name='storagemetric',
            name='fstype',
        ),
        migrations.RemoveField(
            model_name='storagemetric',
            name='mountpoint',
        ),
        migrations.AddField(
            model_name='metricsnapshot',
            name='profile_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
