# Generated by Django 6.0.5 on 2026-06-14 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics_app', '0024_docker_container_created_status'),
    ]

    operations = [
        # LatestDockerContainer: drop table if it exists, delete from Django state
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='LatestDockerContainer',
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='DROP TABLE IF EXISTS metrics_latest_docker_container CASCADE',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
        # Add docker_containers_json to LatestSnapshot
        migrations.AddField(
            model_name='latestsnapshot',
            name='docker_containers_json',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
