# Generated by Django 6.0.6 on 2026-06-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics_app', '0024_docker_container_created_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestsnapshot',
            name='agent_version',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='cpu_load_avg_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='cpu_logical_cores',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='cpu_model',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='cpu_physical_cores',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='mem_cached_bytes',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='mem_free_bytes',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='motherboard_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='software_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='swap_total_bytes',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='swap_used_bytes',
            field=models.BigIntegerField(null=True),
        ),
    ]
