# Generated by Django 6.0.6 on 2026-06-15 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics_app', '0025_add_latestsnapshot_live_metrics_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metricsnapshot',
            name='agent_version',
        ),
        migrations.RemoveField(
            model_name='metricsnapshot',
            name='cpu_logical_cores',
        ),
        migrations.RemoveField(
            model_name='metricsnapshot',
            name='cpu_model',
        ),
        migrations.RemoveField(
            model_name='metricsnapshot',
            name='cpu_physical_cores',
        ),
        migrations.RemoveField(
            model_name='metricsnapshot',
            name='motherboard_json',
        ),
        migrations.RemoveField(
            model_name='metricsnapshot',
            name='software_json',
        ),
    ]
