# Generated by Django 6.0.5 on 2026-06-14 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics_app', '0025_rig_profile_static_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestsnapshot',
            name='uptime_s',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
