# Generated by Django 6.0.5 on 2026-06-15 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics_app', '0026_rig_profile_refactor'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestsnapshot',
            name='swap_total_bytes',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='swap_used_bytes',
            field=models.BigIntegerField(null=True),
        ),
    ]
