# Generated by Django 6.0.6 on 2026-06-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics_app', '0026_remove_metric_snapshot_static_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricsnapshot',
            name='uptime_s',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
