# Generated by Django 6.0.5 on 2026-06-15 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics_app', '0027_add_swap_to_latest_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestsnapshot',
            name='mem_cached_bytes',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='mem_free_bytes',
            field=models.BigIntegerField(null=True),
        ),
    ]
