# Generated by Django 6.0.6 on 2026-06-15
# This migration was applied from a previous branch. The column already exists
# in the database. This file is a placeholder to keep Django's migration
# state consistent.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics_app', '0027_add_metric_snapshot_uptime'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestsnapshot',
            name='gpu_uuids_json',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
