# Generated by Django 6.0.6 on 2026-06-15 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics_app', '0028_add_gpu_uuids_to_latest_snapshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gpumetric',
            name='gpu_uuid',
        ),
    ]
