# Generated by Django 6.0.5 on 2026-06-15 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics_app', '0028_add_mem_swap_to_latest_snapshot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RigProfile',
        ),
    ]
