# Generated by Django 6.0.6 on 2026-06-16 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics_app', '0029_remove_gpumetric_gpu_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestsnapshot',
            name='storage_read_bytes_delta_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='storage_read_iops_delta_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='storage_utilization_pcts_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='storage_write_bytes_delta_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='storage_write_iops_delta_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='storagemetric',
            name='busy_time_ms',
            field=models.PositiveIntegerField(help_text='Cumulative busy time in ms (counter)', null=True),
        ),
        migrations.AddField(
            model_name='storagemetric',
            name='read_bytes',
            field=models.BigIntegerField(help_text='Cumulative bytes read (counter)', null=True),
        ),
        migrations.AddField(
            model_name='storagemetric',
            name='read_bytes_delta',
            field=models.BigIntegerField(help_text='Bytes read since last sample', null=True),
        ),
        migrations.AddField(
            model_name='storagemetric',
            name='read_iops',
            field=models.PositiveIntegerField(help_text='Cumulative read operations (counter)', null=True),
        ),
        migrations.AddField(
            model_name='storagemetric',
            name='read_iops_delta',
            field=models.PositiveIntegerField(help_text='Read operations since last sample', null=True),
        ),
        migrations.AddField(
            model_name='storagemetric',
            name='utilization_pct',
            field=models.FloatField(help_text='Disk utilization % (0-100)', null=True),
        ),
        migrations.AddField(
            model_name='storagemetric',
            name='write_bytes',
            field=models.BigIntegerField(help_text='Cumulative bytes written (counter)', null=True),
        ),
        migrations.AddField(
            model_name='storagemetric',
            name='write_bytes_delta',
            field=models.BigIntegerField(help_text='Bytes written since last sample', null=True),
        ),
        migrations.AddField(
            model_name='storagemetric',
            name='write_iops',
            field=models.PositiveIntegerField(help_text='Cumulative write operations (counter)', null=True),
        ),
        migrations.AddField(
            model_name='storagemetric',
            name='write_iops_delta',
            field=models.PositiveIntegerField(help_text='Write operations since last sample', null=True),
        ),
    ]
