# Generated by Django 6.0.6 on 2026-06-17 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics_app', '0030_disk_io_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestsnapshot',
            name='storage_read_bytes_total_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='storage_read_iops_total_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='storage_write_bytes_total_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='storage_write_iops_total_json',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
