# Generated by Django 6.0.6 on 2026-06-17 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics_app', '0031_latestsnapshot_cumulative_io'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestsnapshot',
            name='process_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='top_cpu_processes_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='top_mem_processes_json',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
