# Generated by Django 6.0.6 on 2026-06-19 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics_app', '0032_latestsnapshot_top_processes'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestsnapshot',
            name='cpu_freq_current_mhz',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='cpu_freq_max_mhz',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='cpu_freq_min_mhz',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
