# Generated by Django 6.0.6 on 2026-06-19 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics_app', '0033_latest_snapshot_cpu_freq'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricsnapshot',
            name='cpu_freq_current_mhz',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metricsnapshot',
            name='cpu_freq_max_mhz',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metricsnapshot',
            name='cpu_freq_min_mhz',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
