# Generated by Django 6.0.6 on 2026-06-23 02:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics_app', '0035_rename_latestsnapshot_table'),
        ('rigs', '0005_rig_electricity_rate_kwh_rig_psu_efficiency'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerReading',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('gpu_power_w', models.FloatField(default=0)),
                ('cpu_power_w', models.FloatField(default=0)),
                ('cpu_power_source', models.CharField(choices=[('rapl', 'RAPL (measured)'), ('estimate', 'Estimated from utilization')], default='rapl', max_length=10)),
                ('cpu_utilization', models.FloatField(default=0)),
                ('cpu_cores', models.PositiveSmallIntegerField(default=0)),
                ('other_power_w', models.FloatField(default=50)),
                ('total_dc_power_w', models.FloatField(default=0)),
                ('total_ac_power_w', models.FloatField(default=0)),
                ('psu_efficiency', models.FloatField(default=0.9)),
                ('rig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='power_readings', to='rigs.rig')),
            ],
            options={
                'db_table': 'metrics_power_reading',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['rig', '-timestamp'], name='metrics_pow_rig_id_a2a8c3_idx')],
            },
        ),
    ]
