# Generated by Django 6.0.6 on 2026-06-23 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics_app', '0036_powerreading'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestsnapshot',
            name='power_cost_per_hour',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='power_cpu_source',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='power_cpu_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='power_gpu_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='power_other_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='power_total_ac_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='power_total_dc_w',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
