# Generated by Django 6.0.6 on 2026-06-23 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics_app', '0037_latestsnapshot_power_cost_per_hour_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='latestsnapshot',
            old_name='power_total_ac_w',
            new_name='power_total_w',
        ),
        migrations.RenameField(
            model_name='powerreading',
            old_name='total_ac_power_w',
            new_name='total_power_w',
        ),
        migrations.RemoveField(
            model_name='latestsnapshot',
            name='power_cost_per_hour',
        ),
        migrations.RemoveField(
            model_name='latestsnapshot',
            name='power_cpu_source',
        ),
        migrations.RemoveField(
            model_name='latestsnapshot',
            name='power_total_dc_w',
        ),
        migrations.RemoveField(
            model_name='powerreading',
            name='psu_efficiency',
        ),
        migrations.RemoveField(
            model_name='powerreading',
            name='total_dc_power_w',
        ),
        migrations.AddField(
            model_name='metricsnapshot',
            name='cpu_power_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metricsnapshot',
            name='total_system_power_w',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
