# Generated by Django 6.0.6 on 2026-06-23 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics_app', '0038_rename_power_total_ac_w_latestsnapshot_power_total_w_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='powerreading',
            name='cpu_cores',
        ),
        migrations.RemoveField(
            model_name='powerreading',
            name='cpu_utilization',
        ),
    ]
