# Generated by Django 6.0.6 on 2026-06-25 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics_app', '0039_remove_powerreading_cpu_cores_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powerreading',
            name='other_power_w',
            field=models.FloatField(default=40),
        ),
    ]
