# Generated by Django 6.0.6 on 2026-06-29 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics_app', '0040_alter_powerreading_other_power_w'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestsnapshot',
            name='storage_busy_time_ms_total_json',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
