# Generated by Django 6.0.6 on 2026-07-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics_app', '0041_add_storage_busy_time_ms_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpumetric',
            name='mem_controller_util_pct',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='gpu_mem_controller_utils_json',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
