# Generated by Django 6.0.6 on 2026-08-27 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics_app', '0042_gpumetric_mem_controller_util_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestdockercontainer',
            name='logs_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='latestdockercontainer',
            name='manifest_json',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
