# Generated by Django 6.0.6 on 2026-08-27 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics_app', '0043_latestdockercontainer_logs_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestsnapshot',
            name='has_active_job',
            field=models.BooleanField(default=False),
        ),
    ]
