# Generated by Django 6.0.6 on 2026-09-15 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics_app', '0052_readd_gpumetric_gpu_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpumetric',
            name='gpu_uuid',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Stable GPU UUID or GPU-prefixed identifier for identity tracking; full value shown in charts', max_length=64),
        ),
    ]
