# Generated by Django 6.1.1 on 2026-09-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics_app', '0054_latest_snapshot_disk_hardware_identifiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpumetric',
            name='gpu_board_part_number',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='gpumetric',
            name='gpu_brand',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='gpu_board_part_numbers_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='gpu_brands_json',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
