# Generated by Django 6.1.1 on 2026-09-30 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics_app', '0055_gpumetric_gpu_brand_board_part'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gpumetric',
            name='gpu_brand',
        ),
        migrations.RemoveField(
            model_name='latestsnapshot',
            name='gpu_brands_json',
        ),
    ]
