# Generated by Django 6.1.1 on 2026-10-01 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics_app', '0056_remove_gpu_brands_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpumetric',
            name='gpu_subvendor',
            field=models.CharField(blank=True, default='', help_text='AIB board partner (e.g. MSI, ASUS, Gigabyte); "" when unknown', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='gpu_subvendors_json',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
