# Generated by Django 6.1.1 on 2026-10-01 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics_app', '0057_gpumetric_gpu_subvendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpumetric',
            name='gpu_architecture',
            field=models.CharField(blank=True, default='', help_text='GPU architecture (e.g. Ampere, Hopper, Ada)', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='gpumetric',
            name='gpu_board_id',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Board ID (0 = unavailable)', null=True),
        ),
        migrations.AddField(
            model_name='gpumetric',
            name='gpu_bus_type',
            field=models.CharField(blank=True, default='', help_text='Bus type: PCIe or NVLink', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='gpumetric',
            name='gpu_inforom',
            field=models.JSONField(blank=True, default=dict, help_text='INFOROM versions (OEM/EFI/VBIOS)', null=True),
        ),
        migrations.AddField(
            model_name='gpumetric',
            name='gpu_pci_subsystem',
            field=models.CharField(blank=True, default='', help_text='PCI subsystem vendor:device (hex)', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='gpumetric',
            name='gpu_serial',
            field=models.CharField(blank=True, default='', help_text='GPU serial number', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='gpumetric',
            name='gpu_vbios',
            field=models.CharField(blank=True, default='', help_text='VBIOS version string', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='gpumetric',
            name='pci_bus_id',
            field=models.CharField(blank=True, default='', help_text='PCIe bus ID (domain:bus:device.function)', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='gpu_architecture_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='gpu_board_ids_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='gpu_bus_type_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='gpu_inforom_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='gpu_pci_bus_ids_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='gpu_pci_subsystems_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='gpu_serials_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='gpu_vbios_json',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
