# Generated by Django 6.1.1 on 2026-10-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics_app', '0058_gpumetric_phase2_static_identifiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpumetric',
            name='gpu_bar1_mb',
            field=models.JSONField(blank=True, default=dict, help_text='BAR1 memory aperture total/used/free (MB); {} when unavailable', null=True),
        ),
        migrations.AddField(
            model_name='gpumetric',
            name='gpu_max_clocks',
            field=models.JSONField(blank=True, default=dict, help_text='Theoretical max clocks per domain (graphics/mem/sm/video, MHz); {} when unavailable', null=True),
        ),
        migrations.AddField(
            model_name='gpumetric',
            name='gpu_mig_mode',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='MIG mode (0=DISABLE, 1=ENABLE); 0 when unavailable', null=True),
        ),
        migrations.AddField(
            model_name='gpumetric',
            name='gpu_pstates_util',
            field=models.JSONField(blank=True, default=dict, help_text='Dynamic P-state residency + transition thresholds (P0..P7); {} when unavailable', null=True),
        ),
        migrations.AddField(
            model_name='gpumetric',
            name='gpu_thermal_thresholds',
            field=models.JSONField(blank=True, default=dict, help_text='Per-sensor thermal thresholds (shutdown/slowdown/mem_max/gpu_max/acoustic_max/gps_current, °C); {} when unavailable', null=True),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='gpu_bar1_mb_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='gpu_max_clocks_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='gpu_mig_modes_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='gpu_pstates_util_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='gpu_thermal_thresholds_json',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
