# Generated by Django 5.2.17 on 2026-10-05 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics_app', '0059_gpumetric_phase3_performance_thermal'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestsnapshot',
            name='cpu_freq_per_core_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='cpu_temp_per_core_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='latestsnapshot',
            name='cpu_utilization_per_core_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='metricsnapshot',
            name='cpu_freq_per_core_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='metricsnapshot',
            name='cpu_temp_per_core_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='metricsnapshot',
            name='cpu_utilization_per_core_json',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
