# Generated by Django 5.2.18 on 2026-10-08 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics_app', '0060_add_cpu_per_core_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpumetric',
            name='vram_bandwidth_saturation',
            field=models.FloatField(blank=True, help_text='Ratio of memory-controller utilization to GPU utilization; computed at ingest from current gpu_util_pct and mem_controller_util_pct; higher values indicate greater memory-bandwidth pressure relative to GPU compute', null=True),
        ),
    ]
