# Generated by Django 5.2.18 on 2026-10-08 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics_app', '0061_add_vram_bandwidth_saturation'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpumetric',
            name='cooling_efficiency_index',
            field=models.FloatField(blank=True, help_text='°C/W — temperature change per watt of GPU power change; higher values indicate a larger temperature response to power changes', null=True),
        ),
        migrations.AddField(
            model_name='gpumetric',
            name='fan_adjusted_cooling_response',
            field=models.FloatField(blank=True, help_text='°C/W — temperature change per watt of GPU power change, adjusted for the change in fan speed; higher values indicate a larger temperature response after accounting for fan-speed changes', null=True),
        ),
    ]
