# Generated by Django 5.2.18 on 2026-10-08 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics_app', '0062_gpumetric_cooling_efficiency_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricsnapshot',
            name='cpu_to_gpu_power_ratio',
            field=models.FloatField(blank=True, help_text='Ratio of CPU power to total GPU power (cpu_power_w / sum(gpu_power_draw_w)); computed at agent from payload power data; higher values indicate CPU draws more power relative to GPUs; single-line chart (not per-GPU)', null=True),
        ),
    ]
